/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `nodejs.yorum`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `yorum`;
CREATE TABLE `yorum` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `email` LONGTEXT,
    `tarih` DATETIME,
    `yazi.0` VARBINARY(12),
    `yorum` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `yorum` (`__v`, `_id`, `email`, `tarih`, `yazi.0`, `yorum`)
    VALUES
        (0, x'5CB9BB7AB9ACDA2D6CF92B36', 'lorem@ipsum.com', '2019-04-20 14:01:28.119000', x'5CB9BB7AB9ACDA2D6CF92B34', 'I love Dimebag Darrell');
INSERT INTO `yorum` (`__v`, `_id`, `email`, `tarih`, `yazi.0`, `yorum`)
    VALUES
        (0, x'5CB9BB7AB9ACDA2D6CF92B37', 'lorem2@ipsum2.com', '2019-04-20 14:01:28.119000', x'5CB9BB7AB9ACDA2D6CF92B35', 'I love Zakk Wylde');
